import {
    MIN_NUMBER_OF_VOTES_FOR_SSW,
    minPercentage,
    PARLIAMENT_SEATS_ELECTION_REFORM,
    PARTY_SONSTIGE
} from "../../../Constants.tsx";
import {DirectMandateWinner, ElectionResult, SeatResult} from "../../../types/ElectionTypes.tsx";
import SeatCalculatorStrategy from "./SeatCalculatorStrategy.tsx";

interface SeatCalculationHelp {
    party: string,
    seats: number
}

export class VoteReformSeatCalculator implements SeatCalculatorStrategy {
    calculate(electionResults: ElectionResult[], directMandateWinners: DirectMandateWinner[]): SeatResult[] {
        const winners = new Set(
            directMandateWinners
                .filter(x => x.districtsWon >= 3)
                .map(x => x.party)
        );
        console.log(directMandateWinners);
        const filteredResults = electionResults
            .filter(r => this.isAllowed(r, winners, MIN_NUMBER_OF_VOTES_FOR_SSW) && r.partyAbbreviation !== PARTY_SONSTIGE)

        // Code generated by DeepSeek. It seems to work, so it should be good enough.
        // Generate all possible quotients
        const quotients: SeatCalculationHelp[] = [];
        filteredResults.forEach(electionResult => {
            for (let i = 0; i < PARLIAMENT_SEATS_ELECTION_REFORM; i++) {
                const divisor = 2 * i + 1;
                quotients.push({
                    party: electionResult.partyAbbreviation,
                    seats: electionResult.votes / divisor
                });
            }
        });

        // Sort quotients descending
        const sorted = [...quotients].sort((a, b) => b.seats - a.seats);

        // Select top quotients
        const selected = sorted.slice(0, PARLIAMENT_SEATS_ELECTION_REFORM);

        // Count seats per party
        const seatCount = selected.reduce<Record<string, number>>((acc, {party}) => ({
            ...acc,
            [party]: (acc[party] || 0) + 1
        }), {});

        return filteredResults.map(r => ({
                partyAbbreviation: r.partyAbbreviation,
                seatNumber: seatCount[r.partyAbbreviation],
                seatPosition: r.seatPosition,
            })
        );
    }

    private isAllowed(r: ElectionResult, winners: Set<string>, minimalNumberOfVotes: number): boolean {
        return r.votes >= minimalNumberOfVotes && (r.percentage > minPercentage || winners.has(r.partyAbbreviation));
    }
}

